version: "3.9"

services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "4002:4002"
    networks:
      - my-shared-network
    restart: always

networks:
  my-shared-network:
    external: true