version: "3.8"

services:

  billing-service:
    build: .
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    external: true
    name: my-shared-network